package com.teknei.util;

public enum ReplyOptions {

	SBOP_TURN, SBOP_ACCE_SALI, SBOP_TRAN, SBOP_TRAN_DIVI, SBOP_CONT_ACCE, SBOP_ASGN_TURN, SBOP_RECA, SBOP_RECA_DIVI, SFRU_ASGN, CAUP_TRAN, CAUP_DIST_POSV, CAUP_TADI_POSV, SFMO_HIST, SFVH_DATA_DIA, SFOP_MSG_COND, SFOP_EQUI_ALAR

}
