package com.teknei.persistence.entities.envi;
// Generated 4/08/2015 05:20:32 PM by Hibernate Tools 4.3.1

import java.security.Timestamp;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Data;

/**
 * SbopTran generated by hbm2java
 */
@Entity
@Table(name = "sbop_cont_acce", schema = "sitm_envi")
@Data
public class EnviSbopContAcce implements java.io.Serializable {

	@EmbeddedId
	private EnviSbopContAccePK id;
	
	@Column(name = "bol_envi")
	private boolean bolEnvi;
	
	@Column(name = "id_envi")
	private Integer idEnvi;
	
	@Column(name = "cod_envi")
	private String codEnvi;
	
	@Column(name = "fch_envi")
	private Timestamp fchEnvi;


}
