package com.teknei.persistence.entities.envi;
// Generated 4/08/2015 05:20:32 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.Data;

/**
 * SbopTranId generated by hbm2java
 */
@Embeddable
@Data
public class EnviSbopContAcceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Column(name = "id_cont_acce", nullable = false)
	private int idContAcce;
	@Column(name = "id_turn", nullable = false)
	private int idTurn;
	@Column(name = "id_equi", nullable = false)
	private int idEqui;


}
